name: Events Demo 1
on: 
  pull_request:
    types:
      - opened
  workflow_dispatch:
  push:
    branches:
      - main
      - master
jobs:
  upload-code:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: upload-code
          path: |
            dist/
            package.json
  deploy-code:
    needs: upload-code
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: upload-code
      - name: Output content of artifacts
        run: ls -l
      - name: Deploy code
        run: echo "Deploying code"