name: Events Demo 1
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  
      name:
        type: choice
        description: Who to greet
        options: 
        - monalisa
        - cschleiden
      message:
        required: true
      use-emoji:
        type: boolean
        description: Include 🎉🤣 emojis
      environment:
        type: environment
  # push:
  #   branches:
  #     - main
  #     - master
jobs:
  upload-code:
    runs-on: ubuntu-latest
    outputs:
      filePath: ${{ steps.my-artifact-name.outputs.my-script }}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Build code
        run: npm run build
      - name: Publish name of the artefact
        id: my-artifact-name
        run: find dist/assets/*.js -type f -execdir echo 'my-script={}' >> $GITHUB_OUTPUT ';'
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: upload-code
          path: |
            dist/
            package.json
  deploy-code:
    needs: upload-code
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: upload-code
      - name: Extract the main file
        run: echo "${{ needs.upload-code.outputs.filePath}}"
      - name: Output content of artifacts
        run: ls -l
      - name: Deploy code
        run: echo "Deploying code"