name: Events Demo 1
on: 
  pull_request:
    types:
      - opened
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - '.github/workflows/*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: download-code
          path: |
            dist/
            package.json
      - name: Deploy project
        run: echo "Deploying..."